name: aws_sso

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust dependencies
        run: rustup component add rustfmt clippy

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test

      - name: Format
        run: cargo fmt --all

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Check
        run: cargo check

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Audit
        run: cargo audit

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN
